### ISSUE TITLE
License

### ISSUE THREAD

**Issue by samuelkarp** [ejholmes/cloudwatch#2]
Hi @ejholmes, this library looks pretty cool.  However, I don't see a license; is it BSD like Go?  (Also, any thought on making the name a bit more specific to CloudWatch Logs rather than just CloudWatch?)

**Comment by ejholmes** [comment]
Good call! Added a license in https://github.com/ejholmes/cloudwatch/commit/d9fa33ec3ae301b718bd637f536df1d3f881a4eb (BSD).

Any suggestions on a new name? Current name was picked quickly and could definitely be better. Closing this for now.

**Comment by samuelkarp** [comment]
Maybe go-cloudwatch-logs or something like that?
